# Generated by Django 3.2.5 on 2021-09-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
