# Generated by Django 3.2.5 on 2021-09-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0013_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, to='final.status'),
        ),
    ]
