# Generated by Django 3.2.5 on 2021-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_auto_20210903_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, default='student'),
        ),
    ]
