# Generated by Django 3.2.5 on 2021-09-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0017_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
