# Generated by Django 3.2.5 on 2021-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0018_auto_20210903_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
